<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/jquery-3.4.1.min.js') }}"></script>
    <script src="{{ asset('js/report.js') }}" defer></script>

    <!-- Fonts -->

    <!-- Disable tap highlight on IE -->
    <meta name="msapplication-tap-highlight" content="no">

    <!-- Styles -->
    <link href="{{ asset('css/leave_statement.css') }}" rel="stylesheet">
    <link href="{{ asset('css/main.css') }}" rel="stylesheet">
    <link href="{{ asset('css/custom.css') }}" rel="stylesheet">
</head>

<body>
<div id="report">
    <div class="toolbar hidden-print">
        <div class="text-right">
            <button id="printReport" class="btn btn-info"><i class="fa fa-print"></i> Print</button>
            <button class="btn btn-info"><i class="fa fa-file-pdf-o"></i> Export as PDF</button>
        </div>
        <hr>
    </div>
    <div class="report overflow-auto pt-0">
        <div style="min-width: 600px">
            <header>
                <div class="row pb-2">
                    <div class="col text-center" >
                        <a target="_blank" href="https://lobianijs.com">
                            <img  src="/images/tmarc_logo.png" data-holder-rendered="true" style="max-height: 150px; width: auto;"/>
                        </a>
                    </div>
                    <div class="col company-details" style="display: none">
                        <div>Plot No. 215/217 Block D</div>
                        <div>Kuringa Drive, Tegeta</div>
                        <div>P.O.Box 63266</div>
                        <div>Dar es Salaam, Tanzania</div>
                        <div>Tel : +255 22 2780870</div>
                        <div>Fax : +255 22 2781296</div>
                        <div>Email: info@tmarc.or.tz</div>
                    </div>
                </div>
            </header>
            <main>

                <div class="row pl-3 pr-3" >
                    <div class="col text-center pt-3 pb-2 " style="background-color: #ddd;">
                        <h3>EMPLOYEE LEAVE APPLICATION</h3>
                    </div>
                </div>

                <div class="row contacts mt-2">
                    <div class="col report-to">
                        <div class="address">Leave No. : <strong>{{strtoupper($leave->id)}}</strong></div>
                        <div>Employee Name : <strong>{{ucwords($leave->staff->first_name.' '.$leave->staff->last_name)}}</strong></div>
                        <div class="date">Department : <strong>{{ucwords($leave->staff->department->name)}}</strong></div>
                        <div class="date">Designation : <strong>{{ucwords($leave->staff->jobTitle->title)}}</strong></div>
                    </div>
                    <div class="col report-details">
                        <div class="date">Generated By : <strong>{{$generated_by}}</strong></div>
                        <div class="date">Generation Date : <strong>{{$generation_date}}</strong></div>
                    </div>
                </div>

                <div class="row">
                    <div class="col-md-12">
                        <table class="table table-hover  table-bordered" border="0" cellspacing="0" cellpadding="0">
                            <thead>
                            <tr>
                                <tr><th class="text-center table-title" colspan="8">LEAVE INFORMATION</th></tr>
                                <tr style="background-color: #efefef;">
                                    <th class="text-left ">Type of Leave</th>
                                    <th class="text-left ">Starting Date</th>
                                    <th class="text-left ">Ending Date</th>
                                    <th class="text-center ">Days Requested</th>
                                    <th class="text-center ">Entitled Days</th>
                                    <th class="text-center ">Days Left</th>
                                    <th class="text-left ">Date of Request</th>
                                    <th class="text-left ">Status</th>
                                </tr>
                            </tr>
                            </thead>
                            <tbody>
                            <tr>
                                @if( count($summary) > 0)
                                <td class="text-left description">{{$leave_types[$leave->type]['name']}}</td>
                                <td class="text-left description">{{date('d-m-Y', strtotime($leave->starting_date))}}</td>
                                <td class="text-left description">{{date('d-m-Y', strtotime($leave->ending_date))}}</td>
                                <td class="text-center description">{{$summary[$leave->type]['days-taken']}}</td>
                                <td class="text-center description">{{$summary[$leave->type]['entitled-days']}}</td>
                                <td class="text-center description">{{$summary[$leave->type]['days-left']}}</td>
                                <td class="text-left description">{{date('d-m-Y h:m A', strtotime($leave->created_at))}}</td>
                                <td class="text-left description">{{$leave_statuses[$leave->status]}}</td>
                                @endif
                            </tr>
                            </tbody>
                            <tfoot>
                            </tfoot>
                        </table>
                    </div>
                </div>

                <div class="row">
                    @if( $leave->status == 50)
                        @if( isset($spv_approval->done_by) && isset($hrm_approval->done_by) && isset($md_approval->done_by) )
                        <div class="col approval-info">
                            <div class="text-secondary font-weight-bold">SUPERVISOR APPROVAL</div>
                            <div>Approved By : <span class="font-weight-bold">{{ucwords($spv->first_name.' '.$spv->last_name)}}</span></div>
                            <div>Department : <span class="font-weight-bold">{{ucwords($spv->department->name)}}</span></div>
                            <div>Designation : <span class="font-weight-bold">{{ucwords($spv->jobTitle->title)}}</span></div>
                            <div>Date Of Approval : <span class="font-weight-bold">{{date('d-m-Y H:m A',strtotime($spv_approval->created_at))}}</span></div>
                            @if($spv_approval->comments != '')<div>Comments : <span class="font-weight-bold">{{$spv_approval->comments}}</span></div>@endif
                        </div>

                        <div class="col approval2-info">
                            <div class="text-secondary font-weight-bold">HUMAN RESOURCE MANAGER APPROVAL</div>
                            <div>Approved By : <span class="font-weight-bold">{{ucwords($hrm->first_name.' '.$hrm->last_name)}}</span></div>
                            <div>Department : <span class="font-weight-bold">{{ucwords($hrm->department->name)}}</span></div>
                            <div>Designation : <span class="font-weight-bold">{{ucwords($hrm->jobTitle->title)}}</span></div>
                            <div>Date Of Approval : <span class="font-weight-bold">{{date('d-m-Y H:m A',strtotime($hrm_approval->created_at))}}</span></div>
                            @if($hrm_approval->comments != '')<div>Comments : <span class="font-weight-bold">{{$hrm_approval->comments}}</span></div>@endif
                        </div>

                        <div class="col approval3-info">
                            <div class="text-secondary font-weight-bold">MANAGING DIRECTOR APPROVAL</div>
                            <div>Approved By : <span class="font-weight-bold">{{ucwords($md->first_name.' '.$md->last_name)}}</span></div>
                            <div>Department : <span class="font-weight-bold">{{ucwords($md->department->name)}}</span></div>
                            <div>Designation : <span class="font-weight-bold">{{ucwords($md->jobTitle->title)}}</span></div>
                            <div>Date Of Approval : <span class="font-weight-bold">{{date('d-m-Y H:m A',strtotime($md_approval->created_at))}}</span></div>
                            @if($md_approval->comments != '')<div>Comments : <span class="font-weight-bold">{{$md_approval->comments}}</span></div>@endif
                        </div>
                        @endif
                    @endif
                </div>
            </main>
            <footer>
                This Leave Application was created on a computer and is valid without the signature and seal.
            </footer>
        </div>
        <!--DO NOT DELETE THIS div. IT is responsible for showing footer always at the bottom-->
        <div></div>
    </div>
</div>
</body>
