<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/jquery-3.4.1.min.js') }}" integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=" crossorigin="anonymous"></script>
    <script src="{{ asset('js/report.js') }}" defer></script>

    <!-- Fonts -->

    <!-- Disable tap highlight on IE -->
    <meta name="msapplication-tap-highlight" content="no">

    <!-- Styles -->
    <link href="{{ asset('css/report.css') }}" rel="stylesheet">
    <link href="{{ asset('css/main.css') }}" rel="stylesheet">
    <link href="{{ asset('css/custom.css') }}" rel="stylesheet">
</head>

<body>
<div id="report">
    <div class="toolbar hidden-print">
        <div class="text-right">
            <button id="printReport" class="btn btn-info"><i class="fa fa-print"></i> Print</button>
            <button class="btn btn-info"><i class="fa fa-file-pdf-o"></i> Export as PDF</button>
        </div>
        <hr>
    </div>
    <div class="report overflow-auto pt-0">
        <div style="min-width: 600px">
            <header>
                <div class="row pb-2">
                    <div class="col report-to">
                        <h4 class="">{{$report_title}}</h4>
                        @if($employee_filter == 'yes') <div class="email">Employee : {{$staff_name}}</div>@endif
                        @if($year_filter == 'yes') <div class="email">Year : {{$year}}</div>@endif
                        @if($month_filter == 'yes') <div class="email">Month : {{$month}}</div>@endif
                    </div>
                    <div class="col text-center" >
                        <a target="_blank" href="https://lobianijs.com">
                            <img  src="/images/tmarc_logo.png" data-holder-rendered="true" style="max-height: 150px; width: auto;"/>
                        </a>
                    </div>
                    <div class="col company-details">
                        <div>Plot No. 215/217 Block D</div>
                        <div>Kuringa Drive, Tegeta</div>
                        <div>P.O.Box 63266</div>
                        <div>Dar es Salaam, Tanzania</div>
                        <div>Tel : +255 22 2780870</div>
                        <div>Fax : +255 22 2781296</div>
                        <div>Email: info@tmarc.or.tz</div>
                        <div>Generated By : {{$generated_by}}</div>
                        <div>Generation Date : {{date('d-m-Y h:m',strtotime($generation_date))}}</div>
                    </div>
                </div>
            </header>
            <main>
                @yield('table')
            </main>
            <footer>

            </footer>
        </div>
        <!--DO NOT DELETE THIS div. IT is responsible for showing footer always at the bottom-->
        <div></div>
    </div>
</div>
</body>
