<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/jquery-3.4.1.min.js') }}"></script>
    <script src="{{ asset('js/report.js') }}" defer></script>

    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.22/pdfmake.min.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/html2canvas/0.4.1/html2canvas.min.js"></script>

    <!-- Fonts -->

    <!-- Disable tap highlight on IE -->
    <meta name="msapplication-tap-highlight" content="no">

    <!-- Styles -->
    <link href="{{ asset('css/request_statement.css') }}" rel="stylesheet">
    <link href="{{ asset('css/main.css') }}" rel="stylesheet">
    <link href="{{ asset('css/custom.css') }}" rel="stylesheet">
</head>

<body>
<div id="report">
    <div class="toolbar hidden-print">
        <div class="text-right print-buttons">
            <button id="printReport" class="btn btn-info"><i class="fa fa-print"></i> Print</button>
            <button class="btn btn-info" id="export_as_pdf"><i class="fa fa-file-pdf-o"></i> Export as PDF</button>
        </div>
        <hr>
    </div>
    <div class="report overflow-auto pt-0" id="statement">
        <div style="min-width: 600px">
            <header>
                <div class="row pb-2">
                    <div class="col text-center" >
                        <a target="_blank" href="https://lobianijs.com">
                            <img  src="/images/tmarc_logo.png" data-holder-rendered="true" style="max-height: 150px; width: auto;"/>
                        </a>
                    </div>
                    <div class="col company-details" style="display: none">
                        <div>Plot No. 215/217 Block D</div>
                        <div>KAHAMA</div>
                        <div>P.O.Box 63266</div>
                        <div>KAHAMA</div>
                        <div>Tel : +255 22 2780870</div>
                        <div>Fax : +255 22 2781296</div>
                        <div>Email: info@shdepha.org.com</div>
                    </div>
                </div>
            </header>
            <main>

                <div class="row pl-3 pr-3" >
                    <div class="col text-center pt-2 pb-2 " style="background-color: #00838F;">
                        <h4 style="color:white;">ADVANCE PAYMENT REQUEST</h4>
                    </div>
                </div>

                <div class="row contacts mt-4">
                    <div class="col report-to">
                        <div class="address" style="display: none;">Request No. : <strong>{{strtoupper($advance_payment_request->no)}}</strong></div>
                        <div class="address">Requested By : <strong>{{$employee_name}}</strong></div>
                    </div>
                    <div class="col report-details">
                        <div class="date">Generated By : <strong>{{$generated_by}}</strong></div>
                        <div class="date">Generation Date : <strong>{{$generation_date}}</strong></div>
                    </div>
                </div>

                <div class="row">
                    <div class="col-md-12">
                        @include("advance_payment_requests.form_display")
                    </div>
                </div>



                @if( $advance_payment_request->status == 50)
                    @if( isset($spv_approval->done_by) && isset($acc_approval->done_by) && isset($fd_approval->done_by) && isset($md_approval->done_by) )

                    <div class="row">
                        <div class="col approval-info">
                            <div class="text-secondary font-weight-bold">SUPERVISOR APPROVAL</div>
                            <div>Approved By : <span class="font-weight-bold">{{ucwords($spv->first_name.' '.$spv->last_name)}}</span></div>
                            <div>Department : <span class="font-weight-bold">{{ucwords($spv->department->name)}}</span></div>
                            <div>Designation : <span class="font-weight-bold">{{ucwords($spv->jobTitle->title)}}</span></div>
                            <div>Date Of Approval : <span class="font-weight-bold">{{date('d-m-Y H:m A',strtotime($spv_approval->created_at))}}</span></div>
                            @if($spv_approval->comments != '')<div>Comments : <span class="font-weight-bold">{{$spv_approval->comments}}</span></div>@endif
                        </div>

                        <div class="col approval3-info">
                            <div class="text-secondary font-weight-bold">ACCOUNTANT APPROVAL</div>
                            <div>Approved By : <span class="font-weight-bold">{{ucwords($acc->first_name.' '.$acc->last_name)}}</span></div>
                            <div>Department : <span class="font-weight-bold">{{ucwords($acc->department->name)}}</span></div>
                            <div>Designation : <span class="font-weight-bold">{{ucwords($acc->jobTitle->title)}}</span></div>
                            <div>Date Of Approval : <span class="font-weight-bold">{{date('d-m-Y H:m A',strtotime($acc_approval->created_at))}}</span></div>
                            @if($acc_approval->comments != '')<div>Comments : <span class="font-weight-bold">{{$acc_approval->comments}}</span></div>@endif
                        </div>
                    </div>

                    <div class="row">
                        <div class="col approval-info">
                            <div class="text-secondary font-weight-bold">FINANCE DIRECTOR APPROVAL</div>
                            <div>Approved By : <span class="font-weight-bold">{{ucwords($fd->first_name.' '.$fd->last_name)}}</span></div>
                            <div>Department : <span class="font-weight-bold">{{ucwords($fd->department->name)}}</span></div>
                            <div>Designation : <span class="font-weight-bold">{{ucwords($fd->jobTitle->title)}}</span></div>
                            <div>Date Of Approval : <span class="font-weight-bold">{{date('d-m-Y H:m A',strtotime($fd_approval->created_at))}}</span></div>
                            @if($fd_approval->comments != '')<div>Comments : <span class="font-weight-bold">{{$fd_approval->comments}}</span></div>@endif
                        </div>

                        <div class="col approval3-info">
                            <div class="text-secondary font-weight-bold">MANAGING DIRECTOR APPROVAL</div>
                            <div>Approved By : <span class="font-weight-bold">{{ucwords($md->first_name.' '.$md->last_name)}}</span></div>
                            <div>Department : <span class="font-weight-bold">{{ucwords($md->department->name)}}</span></div>
                            <div>Designation : <span class="font-weight-bold">{{ucwords($md->jobTitle->title)}}</span></div>
                            <div>Date Of Approval : <span class="font-weight-bold">{{date('d-m-Y H:m A',strtotime($md_approval->created_at))}}</span></div>
                            @if($md_approval->comments != '')<div>Comments : <span class="font-weight-bold">{{$md_approval->comments}}</span></div>@endif
                        </div>
                    </div>
                    @endif
                @endif

            </main>
            <footer>
            </footer>
        </div>
        <!--DO NOT DELETE THIS div. IT is responsible for showing footer always at the bottom-->
        <div></div>
    </div>
</div>

<script>

    //for exporting salary slip as pdf
    $("#export_as_pdf").click( function () {
        var statement_name = $("#salary_slip_name").text();
        statement_name = "Advance Payment Request " + "{{str_replace("/",".",$advance_payment_request->no)}}" + ".pdf";

        html2canvas($('#statement')[0], {
            onrendered: function (canvas) {
                var data = canvas.toDataURL();
                var docDefinition = {
                    content: [{
                        image: data,
                        width: 500,
                        scale: 4
                    }]
                };
                pdfMake.createPdf(docDefinition).download(statement_name);
            }
        });
    });


</script>

</body>
